//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppOrdenCompra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbOrdenCompraEntities1 : DbContext
    {
        public dbOrdenCompraEntities1()
            : base("name=dbOrdenCompraEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Concepto> Conceptoes { get; set; }
        public virtual DbSet<Oden> Odens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
