//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppOrdenCompra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oden()
        {
            this.Conceptoes = new HashSet<Concepto>();
        }
    
        public int id { get; set; }
        public string establecimiento { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string propietario { get; set; }
        public string telefono { get; set; }
        public string nit { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto> Conceptoes { get; set; }
    }
}
